#!/bin/bash

set -e
set -o pipefail

if ! [ -x "$(command -v go)" ]
then
  echo "error: a go binary in \$PATH is required to run newgtlds.go" >&2
  exit 1
fi

BIN_CMD="newgtlds"
PROJECT_ROOT="$(dirname $(dirname "$0"))"

if ! [ -x "$(command $BIN_CMD)" ]
then
  echo "installing newgtlds utility to GOPATH" >&2
  pushd "$PROJECT_ROOT/go"
    go install -v ./...
  popd
fi

if ! [ -x "$(command $BIN_CMD)" ]
then
  echo "installed Go tools module but $BIN_CMD not found on \$PATH..." >&2
  exit 1
fi

newgtlds -overwrite -psl-dat-file="$PROJECT_ROOT/public_suffix_list.dat"
