name: Go Tooling
on:
  push:
  pull_request:
  schedule:
    # Run once a day at 14:00 UTC
    - cron:  '0 14 * * *'
jobs:

  build:
    name: Lint and Unit Test
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: ^1.16

    - name: Check out code
      uses: actions/checkout@v2

    - name: Run golangci-lint
      uses: golangci/golangci-lint-action@v2
      with:
        version: v1.33
        working-directory: go

    - name: Run unit tests
      run: go test -v -race ./...
      working-directory: go
